/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 上传类型：1.聊天资源（7 天过期） 2.非聊天资源（不过期）
 * @param objectKey 对象key
 */


data class T3imapiv1ClientTokenReq (

    /* 上传类型：1.聊天资源（7 天过期） 2.非聊天资源（不过期） */
    @Json(name = "Type")
    val type: java.math.BigDecimal,

    /* 对象key */
    @Json(name = "ObjectKey")
    val objectKey: kotlin.String? = null

)

