/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param roomId 群 ID
 * @param name 视频名称
 * @param url 视频播放地址
 * @param cover 视频封面
 * @param propertySize 视频大小
 */


data class T3imapiv1UploadVideoReq (

    /* 群 ID */
    @Json(name = "RoomId")
    val roomId: kotlin.String,

    /* 视频名称 */
    @Json(name = "Name")
    val name: kotlin.String,

    /* 视频播放地址 */
    @Json(name = "Url")
    val url: kotlin.String,

    /* 视频封面 */
    @Json(name = "Cover")
    val cover: kotlin.String,

    /* 视频大小 */
    @Json(name = "Size")
    val propertySize: kotlin.String

)

