/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param apiCode 业务代码
 * @param apiMessage 接口描述信息
 * @param role 用户在此群的角色：0.游客 10.群成员 20.管理员 30.群主
 */


data class T3imapiv1RoomUserInfoRes (

    /* 业务代码 */
    @Json(name = "ApiCode")
    val apiCode: kotlin.Int,

    /* 接口描述信息 */
    @Json(name = "ApiMessage")
    val apiMessage: kotlin.String,

    /* 用户在此群的角色：0.游客 10.群成员 20.管理员 30.群主 */
    @Json(name = "Role")
    val role: java.math.BigDecimal

)

