/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 
 * @param userRole 用户角色
 * @param nickname 昵称
 * @param username 登录用户名
 * @param avatar 头像
 * @param gender 性别
 * @param version 用户信息版本号，前端修改用户信息时改变
 * @param contactsVersion 通讯录版本号
 * @param token 
 * @param lastLoginTime 最后登录时间
 * @param fansNum 
 * @param collectNum 
 * @param supportNum 
 * @param createVideoNum 
 * @param followNum 
 */


data class T3imapiv1Userinfo (

    @Json(name = "UserId")
    val userId: java.math.BigDecimal,

    /* 用户角色 */
    @Json(name = "UserRole")
    val userRole: java.math.BigDecimal,

    /* 昵称 */
    @Json(name = "Nickname")
    val nickname: kotlin.String,

    /* 登录用户名 */
    @Json(name = "Username")
    val username: kotlin.String,

    /* 头像 */
    @Json(name = "Avatar")
    val avatar: kotlin.String,

    /* 性别 */
    @Json(name = "Gender")
    val gender: java.math.BigDecimal,

    /* 用户信息版本号，前端修改用户信息时改变 */
    @Json(name = "Version")
    val version: java.math.BigDecimal,

    /* 通讯录版本号 */
    @Json(name = "ContactsVersion")
    val contactsVersion: java.math.BigDecimal,

    @Json(name = "Token")
    val token: kotlin.String,

    /* 最后登录时间 */
    @Json(name = "LastLoginTime")
    val lastLoginTime: java.math.BigDecimal,

    @Json(name = "FansNum")
    val fansNum: java.math.BigDecimal? = null,

    @Json(name = "CollectNum")
    val collectNum: java.math.BigDecimal? = null,

    @Json(name = "SupportNum")
    val supportNum: java.math.BigDecimal? = null,

    @Json(name = "CreateVideoNum")
    val createVideoNum: java.math.BigDecimal? = null,

    @Json(name = "FollowNum")
    val followNum: java.math.BigDecimal? = null

)

