/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 消息类型
 * @param message 消息内容
 * @param toUsers 接收者
 */


data class T3imapiv1PushMidReq (

    /* 消息类型 */
    @Json(name = "Type")
    val type: kotlin.Int,

    /* 消息内容 */
    @Json(name = "Message")
    val message: kotlin.String,

    /* 接收者 */
    @Json(name = "ToUsers")
    val toUsers: kotlin.String? = null

)

