/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param roomId 群 id
 * @param lastMessageTime 客户端保存的该群最后一条聊天记录
 */


data class T3imapiv1RoomMsgReq (

    /* 群 id */
    @Json(name = "RoomId")
    val roomId: kotlin.String,

    /* 客户端保存的该群最后一条聊天记录 */
    @Json(name = "LastMessageTime")
    val lastMessageTime: java.math.BigDecimal

)

