/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 
 * @param username 
 * @param nickname 
 * @param avatar 
 * @param gender 
 * @param deleted 
 */


data class T3imapiv1ContactsItem (

    @Json(name = "UserId")
    val userId: kotlin.String? = null,

    @Json(name = "Username")
    val username: kotlin.String? = null,

    @Json(name = "Nickname")
    val nickname: kotlin.String? = null,

    @Json(name = "Avatar")
    val avatar: kotlin.String? = null,

    @Json(name = "Gender")
    val gender: java.math.BigDecimal? = null,

    @Json(name = "Deleted")
    val deleted: java.math.BigDecimal? = null

)

