/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `field` 要修改的字段
 * @param `value` 修改的值
 */


data class T3imapiv1UpdateUserinfoReq (

    /* 要修改的字段 */
    @Json(name = "Field")
    val `field`: kotlin.String? = null,

    /* 修改的值 */
    @Json(name = "Value")
    val `value`: kotlin.String? = null

)

