/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param apiCode 业务代码
 * @param apiMessage 接口描述信息
 * @param userId 
 * @param userRole 用户角色
 * @param nickname 昵称
 * @param username 登录用户名
 * @param avatar 头像
 * @param gender 性别
 * @param birthday 生日
 * @param version 用户信息版本号，前端修改用户信息时改变
 * @param contactsVersion 通讯录版本号
 * @param lastLoginTime 
 * @param fansNum 
 * @param followNum 
 * @param supportNum 
 * @param collectVideoNum 
 * @param createVideoNum 
 */


data class T3imapiv1UserinfoRes (

    /* 业务代码 */
    @Json(name = "ApiCode")
    val apiCode: kotlin.Int,

    /* 接口描述信息 */
    @Json(name = "ApiMessage")
    val apiMessage: kotlin.String,

    @Json(name = "UserId")
    val userId: kotlin.String,

    /* 用户角色 */
    @Json(name = "UserRole")
    val userRole: java.math.BigDecimal,

    /* 昵称 */
    @Json(name = "Nickname")
    val nickname: kotlin.String,

    /* 登录用户名 */
    @Json(name = "Username")
    val username: kotlin.String,

    /* 头像 */
    @Json(name = "Avatar")
    val avatar: kotlin.String,

    /* 性别 */
    @Json(name = "Gender")
    val gender: java.math.BigDecimal,

    /* 生日 */
    @Json(name = "Birthday")
    val birthday: kotlin.String,

    /* 用户信息版本号，前端修改用户信息时改变 */
    @Json(name = "Version")
    val version: java.math.BigDecimal,

    /* 通讯录版本号 */
    @Json(name = "ContactsVersion")
    val contactsVersion: java.math.BigDecimal,

    @Json(name = "LastLoginTime")
    val lastLoginTime: java.math.BigDecimal? = null,

    @Json(name = "FansNum")
    val fansNum: java.math.BigDecimal? = null,

    @Json(name = "FollowNum")
    val followNum: java.math.BigDecimal? = null,

    @Json(name = "SupportNum")
    val supportNum: java.math.BigDecimal? = null,

    @Json(name = "CollectVideoNum")
    val collectVideoNum: java.math.BigDecimal? = null,

    @Json(name = "CreateVideoNum")
    val createVideoNum: java.math.BigDecimal? = null

)

