/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param apiCode 业务代码
 * @param apiMessage 接口描述信息
 * @param token 
 * @param lastLoginTime 最后登录时间
 * @param uid 
 */


data class T3imapiv1UserRegisterRes (

    /* 业务代码 */
    @Json(name = "ApiCode")
    val apiCode: kotlin.Int,

    /* 接口描述信息 */
    @Json(name = "ApiMessage")
    val apiMessage: kotlin.String,

    @Json(name = "Token")
    val token: kotlin.String,

    /* 最后登录时间 */
    @Json(name = "LastLoginTime")
    val lastLoginTime: java.math.BigDecimal,

    @Json(name = "Uid")
    val uid: kotlin.String

)

