/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 被关注者用户 ID
 * @param nickname 被关注者昵称
 * @param avatar 被关注者头像
 */


data class T3imapiv1SubscribeUserList (

    /* 被关注者用户 ID */
    @Json(name = "UserId")
    val userId: kotlin.String,

    /* 被关注者昵称 */
    @Json(name = "Nickname")
    val nickname: kotlin.String,

    /* 被关注者头像 */
    @Json(name = "Avatar")
    val avatar: kotlin.String

)

