/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param topicId 帖子 id
 * @param content 评论内容，限制 200 字
 */


data class T3imapiv1CommentTopicReq (

    /* 帖子 id */
    @Json(name = "TopicId")
    val topicId: java.math.BigDecimal,

    /* 评论内容，限制 200 字 */
    @Json(name = "Content")
    val content: kotlin.String

)

