/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param roomId 群 ID
 * @param userIds 最终成为管理员的那些用户的 id，多个逗号隔开
 */


data class T3imapiv1RoomSetAdminReq (

    /* 群 ID */
    @Json(name = "RoomId")
    val roomId: kotlin.String,

    /* 最终成为管理员的那些用户的 id，多个逗号隔开 */
    @Json(name = "UserIds")
    val userIds: kotlin.String? = null

)

