/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param content 内容，长度限制 200
 * @param photos 图片，多张逗号隔开，最多 9 张
 */


data class T3imapiv1CreateTopicReq (

    /* 内容，长度限制 200 */
    @Json(name = "Content")
    val content: kotlin.String,

    /* 图片，多张逗号隔开，最多 9 张 */
    @Json(name = "Photos")
    val photos: kotlin.String? = null

)

