/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param topicId 动态 id
 * @param page 页码，默认 1
 * @param rows 每页显示条数，默认 10 ，最大 20
 */


data class T3imapiv1TopicCommentListReq (

    /* 动态 id */
    @Json(name = "TopicId")
    val topicId: java.math.BigDecimal,

    /* 页码，默认 1 */
    @Json(name = "Page")
    val page: java.math.BigDecimal? = null,

    /* 每页显示条数，默认 10 ，最大 20 */
    @Json(name = "Rows")
    val rows: java.math.BigDecimal? = null

)

