/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tel 
 * @param telCode 
 * @param username 
 * @param password 
 */


data class T3imapiv1UserLoginReq (

    @Json(name = "Tel")
    val tel: kotlin.String? = null,

    @Json(name = "TelCode")
    val telCode: java.math.BigDecimal? = null,

    @Json(name = "Username")
    val username: kotlin.String? = null,

    @Json(name = "Password")
    val password: kotlin.String? = null

)

