/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param roomId 群 ID
 * @param page 第几页
 */


data class T3imapiv1RoomMessageListReq (

    /* 群 ID */
    @Json(name = "Room_id")
    val roomId: kotlin.String? = null,

    /* 第几页 */
    @Json(name = "Page")
    val page: java.math.BigDecimal? = null

)

