/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param apiCode 业务代码
 * @param apiMessage 接口描述信息
 * @param bannedAll 全员禁言结束时间
 * @param bannedUser 用户个人禁言结束时间
 * @param id 房间 id
 * @param video 群视频
 * @param avatar 群头像
 * @param memberNum 群人数
 * @param roomName 群名称
 * @param roomType 群类型 1.官方群 2.用户群
 * @param showVideo 是否展示视频 1.是 0.否
 * @param isMember 用户是否属于当前群成员
 * @param role 用户在此群的角色：0.游客 10.群成员 20.管理员 30.群主
 * @param defaultGame 群默认游戏
 */


data class T3imapiv1RoomInfoRes (

    /* 业务代码 */
    @Json(name = "ApiCode")
    val apiCode: kotlin.Int,

    /* 接口描述信息 */
    @Json(name = "ApiMessage")
    val apiMessage: kotlin.String,

    /* 全员禁言结束时间 */
    @Json(name = "BannedAll")
    val bannedAll: kotlin.Boolean,

    /* 用户个人禁言结束时间 */
    @Json(name = "BannedUser")
    val bannedUser: kotlin.Boolean,

    /* 房间 id */
    @Json(name = "Id")
    val id: kotlin.String,

    /* 群视频 */
    @Json(name = "Video")
    val video: kotlin.String,

    /* 群头像 */
    @Json(name = "Avatar")
    val avatar: kotlin.String,

    /* 群人数 */
    @Json(name = "MemberNum")
    val memberNum: java.math.BigDecimal,

    /* 群名称 */
    @Json(name = "RoomName")
    val roomName: kotlin.String,

    /* 群类型 1.官方群 2.用户群 */
    @Json(name = "RoomType")
    val roomType: java.math.BigDecimal,

    /* 是否展示视频 1.是 0.否 */
    @Json(name = "ShowVideo")
    val showVideo: java.math.BigDecimal,

    /* 用户是否属于当前群成员 */
    @Json(name = "IsMember")
    val isMember: kotlin.Boolean,

    /* 用户在此群的角色：0.游客 10.群成员 20.管理员 30.群主 */
    @Json(name = "Role")
    val role: java.math.BigDecimal,

    /* 群默认游戏 */
    @Json(name = "DefaultGame")
    val defaultGame: kotlin.String

)

