/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param telCode 国际区号
 * @param country 国家
 */


data class T3imapiv1CountryItemRes (

    /* 国际区号 */
    @Json(name = "TelCode")
    val telCode: java.math.BigDecimal,

    /* 国家 */
    @Json(name = "Country")
    val country: kotlin.String

)

