/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 短信类型：1.注册
 * @param telCode 国际区号
 * @param tel 电话
 */


data class T3imapiv1InternationSmsReq (

    /* 短信类型：1.注册 */
    @Json(name = "Type")
    val type: java.math.BigDecimal,

    /* 国际区号 */
    @Json(name = "TelCode")
    val telCode: kotlin.String,

    /* 电话 */
    @Json(name = "Tel")
    val tel: kotlin.String

)

