/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 视频ID
 * @param videoType 视频类型 1.系统预置 2.用户上传
 * @param name 视频名称
 * @param url 视频地址
 * @param cover 视频封面地址
 * @param propertySize 视频大小
 * @param uploadUser 视频上传者
 * @param uploadUserId 视频上传者用户 id
 * @param uploadTime 上传时间
 */


data class T3imapiv1VideoListItem (

    /* 视频ID */
    @Json(name = "Id")
    val id: java.math.BigDecimal,

    /* 视频类型 1.系统预置 2.用户上传 */
    @Json(name = "VideoType")
    val videoType: java.math.BigDecimal,

    /* 视频名称 */
    @Json(name = "Name")
    val name: kotlin.String,

    /* 视频地址 */
    @Json(name = "Url")
    val url: kotlin.String,

    /* 视频封面地址 */
    @Json(name = "Cover")
    val cover: kotlin.String,

    /* 视频大小 */
    @Json(name = "Size")
    val propertySize: kotlin.String,

    /* 视频上传者 */
    @Json(name = "UploadUser")
    val uploadUser: kotlin.String,

    /* 视频上传者用户 id */
    @Json(name = "UploadUserId")
    val uploadUserId: kotlin.String,

    /* 上传时间 */
    @Json(name = "UploadTime")
    val uploadTime: kotlin.String

)

