/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *
 *
 * @param avatar
 * @param nickname
 * @param userId
 * @param role 用户在此群的角色 10.普通用户 20.群普通管理员 30.群主：
 * @param createTime
 */


data class T3imapiv1RoomMemberListItem(

    @Json(name = "Avatar")
    val avatar: kotlin.String,

    @Json(name = "Nickname")
    val nickname: kotlin.String,

    @Json(name = "UserId")
    val userId: kotlin.String,

    /* 用户在此群的角色 10.普通用户 20.群普通管理员 30.群主： */
    @Json(name = "Role")
    val role: java.math.BigDecimal,

    @Json(name = "CreateTime")
    val createTime: kotlin.String? = null

)

