/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param apiCode 业务代码
 * @param apiMessage 接口描述信息
 * @param userId 
 * @param username 
 * @param nickname 
 * @param avatar 
 */


data class T3imapiv1SearchUserRes (

    /* 业务代码 */
    @Json(name = "ApiCode")
    val apiCode: kotlin.Int,

    /* 接口描述信息 */
    @Json(name = "ApiMessage")
    val apiMessage: kotlin.String,

    @Json(name = "UserId")
    val userId: kotlin.String? = null,

    @Json(name = "Username")
    val username: kotlin.String? = null,

    @Json(name = "Nickname")
    val nickname: kotlin.String? = null,

    @Json(name = "Avatar")
    val avatar: kotlin.String? = null

)

