/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 上传类型：1.安卓 2.ios
 */


data class T3imapiv1VersionReq (

    /* 上传类型：1.安卓 2.ios */
    @Json(name = "Type")
    val type: java.math.BigDecimal

)

