/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param roomId 如果值非空则代表邀请邀请，否则为新创建群
 * @param userIds 邀请的成员，多个逗号隔开
 * @param message 发一条谁邀请了谁的消息到群中
 */


data class T3imapiv1InviteMemberReq (

    /* 如果值非空则代表邀请邀请，否则为新创建群 */
    @Json(name = "RoomId")
    val roomId: kotlin.String? = null,

    /* 邀请的成员，多个逗号隔开 */
    @Json(name = "UserIds")
    val userIds: kotlin.String? = null,

    /* 发一条谁邀请了谁的消息到群中 */
    @Json(name = "Message")
    val message: kotlin.String? = null

)

