/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 用户 id
 * @param type 1.接受 0.拒绝
 */


data class T3imapiv1AddContactsReq (

    /* 用户 id */
    @Json(name = "UserId")
    val userId: kotlin.String,

    /* 1.接受 0.拒绝 */
    @Json(name = "Type")
    val type: kotlin.Int

)

