/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param msgId 
 * @param msgType 
 * @param fromUser 
 * @param content 
 * @param time 
 */


data class T3imapiv1UserMessageListItem (

    @Json(name = "MsgId")
    val msgId: kotlin.String,

    @Json(name = "MsgType")
    val msgType: java.math.BigDecimal,

    @Json(name = "FromUser")
    val fromUser: java.math.BigDecimal,

    @Json(name = "Content")
    val content: kotlin.String,

    @Json(name = "Time")
    val time: java.math.BigDecimal

)

